name: Daily PhantomBuster Scraper and S3 Upload

on:
  schedule:
    - cron: "0 3 * * *"  # Every day at 3:00 AM UTC
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run PhantomBuster scrape script
        env:
          ALL_CREDENTIALS: ${{ secrets.ALL_CREDENTIALS }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: node scrape-and-upload.js
