name: 2 PhantomBuster Run and Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-phantombuster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node dependencies
        run: npm install

      - name: Run PhantomBuster agent (Node.js)
        env:
          ALL_CREDENTIALS: ${{ secrets.ALL_CREDENTIALS }}
          S3_BUCKET_NAME: ${{ fromJson(secrets.ALL_CREDENTIALS).S3_BUCKET_NAME }}
        run: |
          node scrape-and-upload.js

      - name: Upload Phantom output CSV to S3 using Python script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"   # change if your bucket region differs
          # Bucket name is hardcoded in your script, or you can also pass it here if you modify your script
        run: |
          python upload-to-s3.py
