name: PhantomBuster Run and Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'   # Runs every day at 6:00 AM UTC

jobs:
  run-phantombuster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node dependencies
        run: npm install

      - name: Run PhantomBuster agent (Node.js)
        env:
          ALL_CREDENTIALS: ${{ secrets.ALL_CREDENTIALS }}
        run: |
          node scrape-and-upload.js

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests boto3

      - name: Upload Phantom output CSV to S3 using Python script
        env:
          ALL_CREDENTIALS: ${{ secrets.ALL_CREDENTIALS }}
        run: python upload-to-s3.py
